## Que 1. Write Python Programs to use various operators in Python

In [15]:
a = 10
b = 20

# Addition
print(a + b)

# Subtraction
print(a - b)

# Multiplication
print(a * b)

# Division
print(a / b)

# Modulus
print(a % b)

# Exponentiation
print(a ** b)

30
-10
200
0.5
10
100000000000000000000


In [16]:
a = 10
b = 20

# Equality
print(a == b)

# Inequality
print(a != b)

# Greater than
print(a > b)

# Less than
print(a < b)

# Greater than or equal to
print(a >= b)

# Less than or equal to
print(a <= b)

False
True
False
True
False
True


In [17]:
a = True
b = False

# AND
print(a and b)

# OR
print(a or b)

# NOT
print(not a)

False
True
False


In [18]:
a = 'Python'
b = 'thon'

# IN
print('Python' in a)

# NOT IN
print('thon' not in a)

True
False


In [21]:
a = 10

# Arithmetic assignment
a += 10
print(a)

# Subtract assignment
a -= 10
print(a)

# Multiplication assignment
a *= 10
print(a)

# Division assignment
a /= 10
print(a)

# Modulus assignment
a %= 10
print(a)

# Exponentiation assignment
a **= 10
print(a)

20
10
100
10.0
0.0
0.0


## 2. Create list of elements and slice and dice it

In [22]:
elements = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print("Original list:")
print(elements)

# 1. Slice elements from index 2 to index 5 (exclusive)
sliced_elements = elements[2:5]
print("\nSliced elements from index 2 to 4:")
print(sliced_elements)

# 2. Slice elements from the beginning up to index 6 (exclusive)
sliced_beginning = elements[:6]
print("\nSliced elements from the beginning up to index 5:")
print(sliced_beginning)

# 3. Slice elements from index 4 to the end of the list
sliced_end = elements[4:]
print("\nSliced elements from index 4 to the end:")
print(sliced_end)

# 4. Slice elements from index 1 to index 9, skipping every second element
sliced_with_step = elements[1:9:2]
print("\nSliced elements from index 1 to 8, skipping every second element:")
print(sliced_with_step)

# 5. Reverse the list
reversed_elements = elements[::-1]
print("\nReversed elements:")
print(reversed_elements)

# 6. Replace a slice of elements with new values
elements[2:5] = [11, 12, 13]
print("\nModified list after replacing a slice:")
print(elements)

Original list:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Sliced elements from index 2 to 4:
[3, 4, 5]

Sliced elements from the beginning up to index 5:
[1, 2, 3, 4, 5, 6]

Sliced elements from index 4 to the end:
[5, 6, 7, 8, 9, 10]

Sliced elements from index 1 to 8, skipping every second element:
[2, 4, 6, 8]

Reversed elements:
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

Modified list after replacing a slice:
[1, 2, 11, 12, 13, 6, 7, 8, 9, 10]


## 3. Using while loop accept numbers until sum of numbers is less than 100

In [30]:
sum = 0

while sum < 100:
        number = int(input("Enter a number: "))
        sum += number
print("The sum of the numbers is:", sum)

Enter a number: 25
Enter a number: 25
Enter a number: 25
Enter a number: 25
The sum of the numbers is: 100


## 4. Write a python program Read & write Excel files 

In [32]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'London', 'Paris', 'Tokyo']
}

# Convert the data to a DataFrame
d = pd.DataFrame(data)

# Write the DataFrame to an Excel file
d.to_excel('output_file.xlsx', index=False, sheet_name='Sheet1')

In [33]:
d

Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
3    David   40     Tokyo

## 5. Write a python program to scrape reviews from a commercial web site

In [34]:
pip install beautifulsoup4

In [38]:
import requests
from bs4 import BeautifulSoup
def scrape_reviews(url):
    # Send an HTTP GET request to the URL
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        # Parse the HTML content using BeautifulSoup
        soup = BeautifulSoup(response.content, 'html.parser')

        # Find the review elements on the page
        review_elements = soup.find_all('div', class_='review')

        # Extract and print the reviews
        for idx, review_element in enumerate(review_elements, 1):
            review_text = review_element.find('p', class_='review-text').text.strip()
            print(f"Review {idx}: {review_text}")
    else:
        print(f"Failed to fetch data from the URL. Status code: {response.status_code}")

if __name__ == "__main__":
    # Replace 'https://www.example.com/reviews' with the actual URL containing reviews
    website_url = 'https://www.instagram.com/reviews'
    scrape_reviews(website_url)

## 6. Create a 3x3 matrix with values ranging from 2 to 10 using numpy

In [39]:
import numpy as np

# Create a 3x3 matrix
matrix = np.arange(2, 11).reshape(3, 3)

# Print the matrix
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 7. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

In [40]:
import numpy as np

# Create a list of numeric values
list_of_numbers = [1, 2, 3, 4, 5]

# Convert the list into a NumPy array
numpy_array = np.array(list_of_numbers)

# Print the NumPy array
print(numpy_array)

[1 2 3 4 5]


## 8. "Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [42]:
import numpy as np

# Create a null vector of size 10
vector = np.zeros(10)

# Update the sixth value to 11
vector[5] = 11

# Print the vector
print(vector)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]
